### PR TITLE
Added german translation (inital commit v1)

### PR DESCRIPTION
**Pull request by MadByteDE**

### CODE REVIEW

**Comment by tterrag1098** [comment]
Could you please base this branch on 1.10/dev ?

**Comment by MadByteDE** [comment]
Sure.

**Comment by tterrag1098** [comment]
No need to close. You can do it on this one.

**Comment by MadByteDE** [comment]
Sorry, got you wrong. I opened a new branch that is based on the 1.10/dev couple minutes ago (with a newer commit)

**Pull request closed without merging**
