### PR TITLE
Slime block and Bone block variants

### PR DESCRIPTION
**Pull request by ghost**
slime block

slime - lime/normal
slime_1 - black
slime_2 - light gray
slime_3 - brown
slime_4 - pink
slime_5 - yellow
slime_6 - blue
slime_7 - magenta
slime_8 - gray
slime_9 - white
slime_10 - red
slime_11 - orange
slime_12 - green
slime_13 - light blue
slime_14 - cyan
slime_15 - purple

bone block

bone_block_side_battered bone_block_top_battered

### CODE REVIEW

**Comment by tterrag1098** [comment]
Why is this a PR? What are you asking?

**Comment by ghost** [comment]
I thought I could submit ideas here

**Comment by Sunconure11** [comment]
Use issues for that.

Also why did you have to pull like... everything?

**Comment by ghost** [comment]
sorry @Sunconure11 I know there's a guide... but I don't really get it, this is my first 'pull request' Drullkus said something about pull request and forking the repo, idrk. Anyway, do you like the idea or nah?

**Comment by tterrag1098** [comment]
*sigh*

A pull request is how you submit changes to a repository. You do not have any changes to submit, only an idea. The proper place to do this is the 'issues' tab above, not here. What you created here is nonsense, you're trying to merge our own changes into our own repo.

**Comment by ghost** [comment]
Yeh I know I did this in the wrong place/way 
But u dont like the idea?

**Comment by tterrag1098** [comment]
No one ever said that. Just open your suggestion in the correct place, please.

**Pull request closed without merging**
