### PR TITLE
fr_fr.lang file

### PR DESCRIPTION
**Pull request by Xandoria**
Translation of Chisel into French by Xandoria.

### CODE REVIEW

**Comment by tterrag1098** [comment]
Thanks, we really appreciate all the hard work! However, let us fix those translation issues you have pointed out, and you can update this PR to be complete. Is that ok?

**Comment by Xandoria** [comment]
Yes of course!

**Comment by tterrag1098** [comment]
A new release is out with fixed language files.

**Comment by Xandoria** [comment]
Ok, I will download it.

**Comment by Xandoria** [comment]
Ah it's the 1.10 version. Well, I suppose the language file is the same as for the 1.11 version.

**Comment by Xandoria** [comment]
Ah there's new tiles, I really don't want to install Minecraft 1.10 and it's hard to translate without seeing what it's like in the game :(
I'll translate them but it will be approximation.

**Comment by tterrag1098** [comment]
If you'd prefer to wait, a 1.11 release is imminent

**Comment by tterrag1098** [comment]
Actually...we work on 1.10 here, so as to not make maintaining both versions any harder than necessary. So I would actually prefer that this PR be targeted at the default branch (1.10/dev)

**Comment by Xandoria** [comment]
ok i'm half finished on the 1.10 fr_FR

**Comment by Xandoria** [comment]
Finished, I've made a new pull request in the 1.10

**Comment by Xandoria** [comment]
I have noticed that you have uploaded a new version of 1.11 so I can now check for the translation while seeing the blocs. I will let you know shortly.

**Comment by tterrag1098** [comment]
I don't see any new PRs for 1.10

**Comment by Xandoria** [comment]
About dyed glass:

It seems that 2 types of blocks are switched: 
tile.chisel.glassdyedblack.rough.desc.1
tile.chisel.glassdyedblack.streaks.desc.1
because I double checked the translation and in the game the blocks seem to be switched
they are switched also for the other colors of glass

About brownstone:

-Is it supposed to be light when normal and dark when used? I would have thought it would be the contrary but maybe I am mistaken
-Maybe you could add the line
tile.chisel.brownstone.block.desc.2=Has CTM
-There exists no weathered version of tile.chisel.brownstone.block.desc.1=Big Tiled but maybe it was intended that way
-There exists no normal version of tile.chisel.brownstone.weathered-block.desc.1=Weathered Big Tile (because this one does not have CTM, it's a regular tile)
I found all this is a bit confusing...

Other bugs:

-I have translated all the cobblestoneextra but they remain in English in the game so maybe the name of the variable is incorrect in the lang file
-Same thing for limestoneextra
-And for chiseled stone too..., so I suggest veryfying all "extra" variables

-There is a missing description for 1 chiseled stone

**Comment by Xandoria** [comment]
The previous fr_fr.lang file I have uploaded will be replaced by another one since my description of the brownstone was not to my liking now that I have seen what they really look like. But I am awaiting your feedback about my previous message before uploading.

**Comment by tterrag1098** [comment]
>-Maybe you could add the line
tile.chisel.brownstone.block.desc.2=Has CTM

Actually you could just add it, our code will read as many description lines as you provide. 

For everything else, I defer to @Drullkus

**Comment by Drullkus** [comment]
1.10 has some blocks with 'extra' in their block id strings while the 1.11 versions don't. That's probably confusing and I apologize.

The Streaks and Rough are correct. The Streaks one has no borders and Rough has higher contrast in the transparency layer, so the lines plus the border are more solid than the rest. Sorry if that's also confusing. Honestly all of these damn blocks don't need names but it's less confusing than giving them numbers. I'm the artist for these blocks and I know them in my heart like they're my children. Anyway my apologies for this confusion.

The 'Big Tile' thing with Brownstone... there exists a CTM file for the regular big one, but not the weathered or half-weathered. I didn't make these textures, I don't know why they weren't made... but I'll fix that. Otherwise pretty much every big tile in the mod has CTM. These two without CTM are actually pretty much the exception. My apologies if that confused as well.

Thank you for taking the time to translate these though. Do you have a twitter?

**Comment by Drullkus** [comment]
I apologize about apologizing too much. :D

**Comment by Drullkus** [comment]
Just to back one of the things tterrag said, you're allowed to add any amount of lines you want, thanks to how we handle our Block tooltip strings. 

`tile.chisel.blockID.variationID.desc.n=Whatever you wanna say`

Seems you're already familiarized with our formatting. You can easily use this to break up really long strings into multi-lined ones. The Block ID string, the Variation string, and the line number (`n`).

**Comment by Drullkus** [comment]
Could you show me which Chiseled Stone has the missing desc? Like a ingame screenshot? I tried looking earlier but it seems I missed it.

**Comment by Xandoria** [comment]
> 1.10 has some blocks with 'extra' in their block id strings while the 1.11 versions don't. That's probably confusing and I apologize.

ohhhh so you mean the lang file for 1.10 is different than 1.11 :(
that is so not cool because i took the 1.10 en_EN.lang to make the fr_fr.lang this time and I checked, copyed and pasted every entry from my old file to be certain i would'nt make any mistake, thinking that this would be ok to use it in 1.11
*crying*
ok i'll make adjustments...

I thought I had uploaded and made a pull request for the 1.10 lang file, I will do it again, Sorry, I am still a github newb.

Here is a screenshot of the unknown chiseled stone in 1.11, but with my 1.10 lang file...
roche_inconnue

>The Streaks and Rough are correct. The Streaks one has no borders and Rough has higher contrast in the transparency layer, so the lines plus the border are more solid than the rest. Sorry if that's also confusing. Honestly all of these damn blocks don't need names but it's less confusing than giving them numbers. I'm the artist for these blocks and I know them in my heart like they're my children. Anyway my apologies for this confusion.

I will modifiy my translation to better describe your concept.

>

    -Maybe you could add the line
    tile.chisel.brownstone.block.desc.2=Has CTM

>Actually you could just add it, our code will read as many description lines as you provide.

I didn't know I could. I will, then :)

**Comment by Drullkus** [comment]
Just do both 1.11 and 1.10 keys in the Lang file in the 1.10 branch. The differences are literally the blocks with the 'extra' in their names. I think.

**Comment by Xandoria** [comment]
French update for 1.11 by Xandoria

**Comment by Xandoria** [comment]
Ok i've finished and uploaded the files for branches 1.10 and 1.11
I hope everything is ok now :)

**Comment by Xandoria** [comment]
And many thanks for your incredible work on this mod!

**Comment by tterrag1098** [comment]
I merged this PR manually to keep this branch purely ahead of 1.10. You still have credit on the changes and in the commit title. Thank you!

**Pull request closed without merging**
