### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**

### CODE REVIEW

**Comment by Drullkus** [comment]
Lang keys all look good. Will pull when I can.

**Comment by Drullkus** [comment]
Bloody hell. I never pulled this. So sorry!

**Comment by 3TUSK** [comment]
well we always forget something though. that's still okay :)

**Comment by Drullkus** [comment]
Do you have a twitter?

**Comment by 3TUSK** [comment]
Unfortunately I am not a fun of twitter/facebook/snapchat/etc.. Sometimes I am active as `TriTUSK` on #FTB-Wiki at esper.net though. (Apparantly nickname cannot start with number)

**Comment by Drullkus** [comment]
Ah, good enough. [I mentioned you in this tweet on twitter](https://twitter.com/Drullkus/status/763463133482463232).

**Comment by 3TUSK** [comment]
Oh thanks

**Pull request merged**
