### PR TITLE
Added The Has CTM lore to more blocks as it's something that's good to know when building

### PR DESCRIPTION
**Pull request by MarcusElg**
W.I.P
The CTM Lore has currently been added to:
All metals
Antiblocks

This is just to see if your intrested in this change, if you are I will continue will more blocks

### CODE REVIEW

**Comment by Drullkus** [comment]
It's not a half-bad idea but also mind that resource packs can change the blocks so different blocks can get CTM. The tooltip Lang will need to be automatically inserted by Chisel and added if the block truly does have CTM. It's kind of "cluttering" too, so I'd recommend it shows up when you hold shift.

**Comment by MarcusElg** [comment]
Oops it added some more things from my brach :/

**Comment by MarcusElg** [comment]
It's a good idea that it's only shown when holding shift. Also it would be best if it was part of the code as you said

**Comment by MarcusElg** [comment]
How do I stop it from adding all the changes from my branch?

**Comment by Drullkus** [comment]
In IntelliJ you can choose which files to commit and which ones you don't. 

And yes, is recommend if it were done in the code.

I'll take care of the Dark Prismarine textures myself too.

**Comment by tterrag1098** [comment]
I'd rather implement this as a general solution, instead of having the same text translated 100 times in the lang file.

**Pull request closed without merging**
