### PR TITLE
Add Biomes O' Plenty Crag Rock variants

### PR DESCRIPTION
**Pull request by codewarrior0**
Just some recolored cobblestone that matches Crag Rock.

image

### CODE REVIEW

**Comment by Drullkus** [comment]
:+1:

**Comment by Drullkus** [comment]
I may exclude one or two of these in favor of adding one or two of my personal variations, but otherwise this is actually pretty good. :)

**Comment by Drullkus** [comment]
Crap, I had to revert the merge because you sent it to the 1.7-dev repo, not the 3.0-dev repo :(

Can you resend the PR to the 3.0 dev repo? Thanks :)

**Comment by tterrag1098** [comment]
No, don't. Let me fix it -_-

**Comment by tterrag1098** [comment]
Actually, wait. Yes, please make this PR on dev-3.0, not dev. I'll get rid of drullkus' derps.

**Comment by codewarrior0** [comment]
No problem.

**Pull request merged**
